parameters:
#    tracker_role.example.class: Tracker\RoleBundle\Example

services:
#    tracker_role.example:
#        class: %tracker_role.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
