security:
    encoders:
        Tracker\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

        Tracker\UserBundle\Security\User\WebserviceUser:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_provider:
            id: platform.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username
        webservice:
            id: webservice_user_provider


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        oauth_token:
            pattern:    ^/ooo
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true




    access_control:
        - { path: ^/ooo, roles: [ IS_AUTHENTICATED_FULLY  ] }
        - { path: ^/iii, roles: [ IS_AUTHENTICATED_FULLY  ] }
