parameters:
#    tracker_tracker_api.example.class: Tracker\TrackerApiBundle\Example

services:
#    tracker_tracker_api.example:
#        class: %tracker_tracker_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
