parameters:
#    tracker_project.example.class: Tracker\ProjectBundle\Example

services:
#    tracker_project.example:
#        class: %tracker_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
